package com.awooga.ProfilesPaperGui;

import lombok.Builder;
import org.bukkit.*;
import org.bukkit.advancement.Advancement;
import org.bukkit.advancement.AdvancementProgress;
import org.bukkit.attribute.Attribute;
import org.bukkit.attribute.AttributeInstance;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.block.PistonMoveReaction;
import org.bukkit.block.data.BlockData;
import org.bukkit.conversations.Conversation;
import org.bukkit.conversations.ConversationAbandonedEvent;
import org.bukkit.entity.*;
import org.bukkit.entity.memory.MemoryKey;
import org.bukkit.event.entity.EntityDamageEvent;
import org.bukkit.event.player.PlayerTeleportEvent;
import org.bukkit.inventory.*;
import org.bukkit.map.MapView;
import org.bukkit.metadata.MetadataValue;
import org.bukkit.permissions.Permission;
import org.bukkit.permissions.PermissionAttachment;
import org.bukkit.permissions.PermissionAttachmentInfo;
import org.bukkit.persistence.PersistentDataContainer;
import org.bukkit.plugin.Plugin;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;
import org.bukkit.scoreboard.Scoreboard;
import org.bukkit.util.BoundingBox;
import org.bukkit.util.RayTraceResult;
import org.bukkit.util.Vector;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.net.InetSocketAddress;
import java.util.*;

@Builder
public class ProfilePlayerImpl implements Player, OfflinePlayer {
	Player actualPlayer;

	UUID overrideUuid;

	@Override
	public @NotNull UUID getUniqueId() {
		if(Objects.nonNull(this.overrideUuid)) {
			return this.overrideUuid;
		} else {
			return actualPlayer.getUniqueId();
		}
	}

	// =====================================================
	// EVERYTHING BELOW HERE IS AN AUTOGENERATED DELEGATOR.
	// IF YOU MUST MODIFY A FUNCTION BELOW HERE, MOVE IT ABOVE THIS FOLD
	// =====================================================

	@Override
	public float getAttackCooldown() {
		return actualPlayer.getAttackCooldown();
	}

	@Override
	@Deprecated
	public @NotNull String getDisplayName() {
		return actualPlayer.getDisplayName();
	}

	@Override
	@Deprecated
	public void setDisplayName(String name) {
		actualPlayer.setDisplayName(name);
	}

	@Override
	@Deprecated
	public @NotNull String getPlayerListName() {
		return actualPlayer.getPlayerListName();
	}

	@Override
	@Deprecated
	public void setPlayerListName(String name) {
		actualPlayer.setPlayerListName(name);
	}

	@Override
	@Deprecated
	public String getPlayerListHeader() {
		return actualPlayer.getPlayerListHeader();
	}

	@Override
	@Deprecated
	public String getPlayerListFooter() {
		return actualPlayer.getPlayerListFooter();
	}

	@Override
	@Deprecated
	public void setPlayerListHeader(String header) {
		actualPlayer.setPlayerListHeader(header);
	}

	@Override
	@Deprecated
	public void setPlayerListFooter(String footer) {
		actualPlayer.setPlayerListFooter(footer);
	}

	@Override
	@Deprecated
	public void setPlayerListHeaderFooter(String header, String footer) {
		actualPlayer.setPlayerListHeaderFooter(header, footer);
	}

	@Override
	public void setCompassTarget(@NotNull Location loc) {
		actualPlayer.setCompassTarget(loc);
	}

	@Override
	public @NotNull Location getCompassTarget() {
		return actualPlayer.getCompassTarget();
	}

	@Override
	public InetSocketAddress getAddress() {
		return actualPlayer.getAddress();
	}

	@Override
	public void sendRawMessage(@NotNull String message) {
		actualPlayer.sendRawMessage(message);
	}

	@Override
	public void sendRawMessage(@Nullable UUID sender, @NotNull String message) {
		actualPlayer.sendRawMessage(sender, message);
	}

	@Override
	@Deprecated
	public void kickPlayer(String message) {
		actualPlayer.kickPlayer(message);
	}

	@Override
	public void chat(@NotNull String msg) {
		actualPlayer.chat(msg);
	}

	@Override
	public boolean performCommand(@NotNull String command) {
		return actualPlayer.performCommand(command);
	}

	@Override
	public boolean isSneaking() {
		return actualPlayer.isSneaking();
	}

	@Override
	public void setSneaking(boolean sneak) {
		actualPlayer.setSneaking(sneak);
	}

	@Override
	public boolean isSprinting() {
		return actualPlayer.isSprinting();
	}

	@Override
	public void setSprinting(boolean sprinting) {
		actualPlayer.setSprinting(sprinting);
	}

	@Override
	public void saveData() {
		actualPlayer.saveData();
	}

	@Override
	public void loadData() {
		actualPlayer.loadData();
	}

	@Override
	public void setSleepingIgnored(boolean isSleeping) {
		actualPlayer.setSleepingIgnored(isSleeping);
	}

	@Override
	public boolean isSleepingIgnored() {
		return actualPlayer.isSleepingIgnored();
	}

	@Override
	@Deprecated
	public void playNote(@NotNull Location loc, byte instrument, byte note) {
		actualPlayer.playNote(loc, instrument, note);
	}

	@Override
	public void playNote(@NotNull Location loc, @NotNull Instrument instrument, @NotNull Note note) {
		actualPlayer.playNote(loc, instrument, note);
	}

	@Override
	public void playSound(@NotNull Location location, @NotNull Sound sound, float volume, float pitch) {
		actualPlayer.playSound(location, sound, volume, pitch);
	}

	@Override
	public void playSound(@NotNull Location location, @NotNull String sound, float volume, float pitch) {
		actualPlayer.playSound(location, sound, volume, pitch);
	}

	@Override
	public void playSound(@NotNull Location location, @NotNull Sound sound, @NotNull SoundCategory category, float volume, float pitch) {
		actualPlayer.playSound(location, sound, category, volume, pitch);
	}

	@Override
	public void playSound(@NotNull Location location, @NotNull String sound, @NotNull SoundCategory category, float volume, float pitch) {
		actualPlayer.playSound(location, sound, category, volume, pitch);
	}

	@Override
	public void stopSound(@NotNull Sound sound) {
		actualPlayer.stopSound(sound);
	}

	@Override
	public void stopSound(@NotNull String sound) {
		actualPlayer.stopSound(sound);
	}

	@Override
	public void stopSound(@NotNull Sound sound, SoundCategory category) {
		actualPlayer.stopSound(sound, category);
	}

	@Override
	public void stopSound(@NotNull String sound, SoundCategory category) {
		actualPlayer.stopSound(sound, category);
	}

	@Override
	@Deprecated
	public void playEffect(@NotNull Location loc, @NotNull Effect effect, int data) {
		actualPlayer.playEffect(loc, effect, data);
	}

	@Override
	public <T> void playEffect(@NotNull Location loc, @NotNull Effect effect, T data) {
		actualPlayer.playEffect(loc, effect, data);
	}

	@Override
	@Deprecated
	public void sendBlockChange(@NotNull Location loc, @NotNull Material material, byte data) {
		actualPlayer.sendBlockChange(loc, material, data);
	}

	@Override
	public void sendBlockChange(@NotNull Location loc, @NotNull BlockData block) {
		actualPlayer.sendBlockChange(loc, block);
	}

	@Override
	public void sendBlockDamage(@NotNull Location loc, float progress) {
		actualPlayer.sendBlockDamage(loc, progress);
	}

	@Override
	@Deprecated
	public boolean sendChunkChange(@NotNull Location loc, int sx, int sy, int sz, byte[] data) {
		return actualPlayer.sendChunkChange(loc, sx, sy, sz, data);
	}

	@Override
	@Deprecated
	public void sendSignChange(@NotNull Location loc, String[] lines) throws IllegalArgumentException {
		actualPlayer.sendSignChange(loc, lines);
	}

	@Override
	@Deprecated
	public void sendSignChange(@NotNull Location loc, String[] lines, @NotNull DyeColor dyeColor) throws IllegalArgumentException {
		actualPlayer.sendSignChange(loc, lines, dyeColor);
	}

	@Override
	public void sendMap(@NotNull MapView map) {
		actualPlayer.sendMap(map);
	}

	@Override
	public void updateInventory() {
		actualPlayer.updateInventory();
	}

	@Override
	public void setPlayerTime(long time, boolean relative) {
		actualPlayer.setPlayerTime(time, relative);
	}

	@Override
	public long getPlayerTime() {
		return actualPlayer.getPlayerTime();
	}

	@Override
	public long getPlayerTimeOffset() {
		return actualPlayer.getPlayerTimeOffset();
	}

	@Override
	public boolean isPlayerTimeRelative() {
		return actualPlayer.isPlayerTimeRelative();
	}

	@Override
	public void resetPlayerTime() {
		actualPlayer.resetPlayerTime();
	}

	@Override
	public void setPlayerWeather(@NotNull WeatherType type) {
		actualPlayer.setPlayerWeather(type);
	}

	@Override
	public WeatherType getPlayerWeather() {
		return actualPlayer.getPlayerWeather();
	}

	@Override
	public void resetPlayerWeather() {
		actualPlayer.resetPlayerWeather();
	}

	@Override
	public void giveExp(int amount) {
		actualPlayer.giveExp(amount);
	}

	@Override
	public void giveExpLevels(int amount) {
		actualPlayer.giveExpLevels(amount);
	}

	@Override
	public float getExp() {
		return actualPlayer.getExp();
	}

	@Override
	public void setExp(float exp) {
		actualPlayer.setExp(exp);
	}

	@Override
	public int getLevel() {
		return actualPlayer.getLevel();
	}

	@Override
	public void setLevel(int level) {
		actualPlayer.setLevel(level);
	}

	@Override
	public int getTotalExperience() {
		return actualPlayer.getTotalExperience();
	}

	@Override
	public void setTotalExperience(int exp) {
		actualPlayer.setTotalExperience(exp);
	}

	@Override
	public void sendExperienceChange(float progress) {
		actualPlayer.sendExperienceChange(progress);
	}

	@Override
	public void sendExperienceChange(float progress, int level) {
		actualPlayer.sendExperienceChange(progress, level);
	}

	@Override
	public float getExhaustion() {
		return actualPlayer.getExhaustion();
	}

	@Override
	public void setExhaustion(float value) {
		actualPlayer.setExhaustion(value);
	}

	@Override
	public float getSaturation() {
		return actualPlayer.getSaturation();
	}

	@Override
	public void setSaturation(float value) {
		actualPlayer.setSaturation(value);
	}

	@Override
	public int getFoodLevel() {
		return actualPlayer.getFoodLevel();
	}

	@Override
	public void setFoodLevel(int value) {
		actualPlayer.setFoodLevel(value);
	}

	@Override
	public int getSaturatedRegenRate() {
		return actualPlayer.getSaturatedRegenRate();
	}

	@Override
	public void setSaturatedRegenRate(int ticks) {
		actualPlayer.setSaturatedRegenRate(ticks);
	}

	@Override
	public int getUnsaturatedRegenRate() {
		return actualPlayer.getUnsaturatedRegenRate();
	}

	@Override
	public void setUnsaturatedRegenRate(int ticks) {
		actualPlayer.setUnsaturatedRegenRate(ticks);
	}

	@Override
	public int getStarvationRate() {
		return actualPlayer.getStarvationRate();
	}

	@Override
	public void setStarvationRate(int ticks) {
		actualPlayer.setStarvationRate(ticks);
	}

	@Override
	public boolean getAllowFlight() {
		return actualPlayer.getAllowFlight();
	}

	@Override
	public void setAllowFlight(boolean flight) {
		actualPlayer.setAllowFlight(flight);
	}

	@Override
	@Deprecated
	public void hidePlayer(@NotNull Player player) {
		actualPlayer.hidePlayer(player);
	}

	@Override
	public void hidePlayer(@NotNull Plugin plugin, @NotNull Player player) {
		actualPlayer.hidePlayer(plugin, player);
	}

	@Override
	@Deprecated
	public void showPlayer(@NotNull Player player) {
		actualPlayer.showPlayer(player);
	}

	@Override
	public void showPlayer(@NotNull Plugin plugin, @NotNull Player player) {
		actualPlayer.showPlayer(plugin, player);
	}

	@Override
	public boolean canSee(@NotNull Player player) {
		return actualPlayer.canSee(player);
	}

	@Override
	public boolean isFlying() {
		return actualPlayer.isFlying();
	}

	@Override
	public void setFlying(boolean value) {
		actualPlayer.setFlying(value);
	}

	@Override
	public void setFlySpeed(float value) throws IllegalArgumentException {
		actualPlayer.setFlySpeed(value);
	}

	@Override
	public void setWalkSpeed(float value) throws IllegalArgumentException {
		actualPlayer.setWalkSpeed(value);
	}

	@Override
	public float getFlySpeed() {
		return actualPlayer.getFlySpeed();
	}

	@Override
	public float getWalkSpeed() {
		return actualPlayer.getWalkSpeed();
	}

	@Override
	@Deprecated
	public void setTexturePack(@NotNull String url) {
		actualPlayer.setTexturePack(url);
	}

	@Override
	@Deprecated
	public void setResourcePack(@NotNull String url) {
		actualPlayer.setResourcePack(url);
	}

	@Override
	public void setResourcePack(@NotNull String url, byte[] hash) {
		actualPlayer.setResourcePack(url, hash);
	}

	@Override
	public @NotNull Scoreboard getScoreboard() {
		return actualPlayer.getScoreboard();
	}

	@Override
	public void setScoreboard(@NotNull Scoreboard scoreboard) throws IllegalArgumentException, IllegalStateException {
		actualPlayer.setScoreboard(scoreboard);
	}

	@Override
	public boolean isHealthScaled() {
		return actualPlayer.isHealthScaled();
	}

	@Override
	public void setHealthScaled(boolean scale) {
		actualPlayer.setHealthScaled(scale);
	}

	@Override
	public void setHealthScale(double scale) throws IllegalArgumentException {
		actualPlayer.setHealthScale(scale);
	}

	@Override
	public double getHealthScale() {
		return actualPlayer.getHealthScale();
	}

	@Override
	public Entity getSpectatorTarget() {
		return actualPlayer.getSpectatorTarget();
	}

	@Override
	public void setSpectatorTarget(Entity entity) {
		actualPlayer.setSpectatorTarget(entity);
	}

	@Override
	@Deprecated
	public void sendTitle(String title, String subtitle) {
		actualPlayer.sendTitle(title, subtitle);
	}

	@Override
	public void sendTitle(String title, String subtitle, int fadeIn, int stay, int fadeOut) {
		actualPlayer.sendTitle(title, subtitle, fadeIn, stay, fadeOut);
	}

	@Override
	public void resetTitle() {
		actualPlayer.resetTitle();
	}

	@Override
	public void spawnParticle(@NotNull Particle particle, @NotNull Location location, int count) {
		actualPlayer.spawnParticle(particle, location, count);
	}

	@Override
	public void spawnParticle(@NotNull Particle particle, double x, double y, double z, int count) {
		actualPlayer.spawnParticle(particle, x, y, z, count);
	}

	@Override
	public <T> void spawnParticle(@NotNull Particle particle, @NotNull Location location, int count, T data) {
		actualPlayer.spawnParticle(particle, location, count, data);
	}

	@Override
	public <T> void spawnParticle(@NotNull Particle particle, double x, double y, double z, int count, T data) {
		actualPlayer.spawnParticle(particle, x, y, z, count, data);
	}

	@Override
	public void spawnParticle(@NotNull Particle particle, @NotNull Location location, int count, double offsetX, double offsetY, double offsetZ) {
		actualPlayer.spawnParticle(particle, location, count, offsetX, offsetY, offsetZ);
	}

	@Override
	public void spawnParticle(@NotNull Particle particle, double x, double y, double z, int count, double offsetX, double offsetY, double offsetZ) {
		actualPlayer.spawnParticle(particle, x, y, z, count, offsetX, offsetY, offsetZ);
	}

	@Override
	public <T> void spawnParticle(@NotNull Particle particle, @NotNull Location location, int count, double offsetX, double offsetY, double offsetZ, T data) {
		actualPlayer.spawnParticle(particle, location, count, offsetX, offsetY, offsetZ, data);
	}

	@Override
	public <T> void spawnParticle(@NotNull Particle particle, double x, double y, double z, int count, double offsetX, double offsetY, double offsetZ, T data) {
		actualPlayer.spawnParticle(particle, x, y, z, count, offsetX, offsetY, offsetZ, data);
	}

	@Override
	public void spawnParticle(@NotNull Particle particle, @NotNull Location location, int count, double offsetX, double offsetY, double offsetZ, double extra) {
		actualPlayer.spawnParticle(particle, location, count, offsetX, offsetY, offsetZ, extra);
	}

	@Override
	public void spawnParticle(@NotNull Particle particle, double x, double y, double z, int count, double offsetX, double offsetY, double offsetZ, double extra) {
		actualPlayer.spawnParticle(particle, x, y, z, count, offsetX, offsetY, offsetZ, extra);
	}

	@Override
	public <T> void spawnParticle(@NotNull Particle particle, @NotNull Location location, int count, double offsetX, double offsetY, double offsetZ, double extra, T data) {
		actualPlayer.spawnParticle(particle, location, count, offsetX, offsetY, offsetZ, extra, data);
	}

	@Override
	public <T> void spawnParticle(@NotNull Particle particle, double x, double y, double z, int count, double offsetX, double offsetY, double offsetZ, double extra, T data) {
		actualPlayer.spawnParticle(particle, x, y, z, count, offsetX, offsetY, offsetZ, extra, data);
	}

	@Override
	public @NotNull AdvancementProgress getAdvancementProgress(@NotNull Advancement advancement) {
		return actualPlayer.getAdvancementProgress(advancement);
	}

	@Override
	public int getClientViewDistance() {
		return actualPlayer.getClientViewDistance();
	}

	@Override
	public int getPing() {
		return actualPlayer.getPing();
	}

	@Override
	@Deprecated
	public @NotNull String getLocale() {
		return actualPlayer.getLocale();
	}

	@Override
	public void updateCommands() {
		actualPlayer.updateCommands();
	}

	@Override
	public void openBook(@NotNull ItemStack book) {
		actualPlayer.openBook(book);
	}

	@Override
	public @NotNull Spigot spigot() {
		return actualPlayer.spigot();
	}

	@Override
	public @NotNull String getName() {
		return actualPlayer.getName();
	}

	@Override
	public @NotNull PlayerInventory getInventory() {
		return actualPlayer.getInventory();
	}

	@Override
	public @NotNull Inventory getEnderChest() {
		return actualPlayer.getEnderChest();
	}

	@Override
	public @NotNull MainHand getMainHand() {
		return actualPlayer.getMainHand();
	}

	@Override
	public boolean setWindowProperty(InventoryView.@NotNull Property prop, int value) {
		return actualPlayer.setWindowProperty(prop, value);
	}

	@Override
	public @NotNull InventoryView getOpenInventory() {
		return actualPlayer.getOpenInventory();
	}

	@Override
	public InventoryView openInventory(@NotNull Inventory inventory) {
		return actualPlayer.openInventory(inventory);
	}

	@Override
	public InventoryView openWorkbench(Location location, boolean force) {
		return actualPlayer.openWorkbench(location, force);
	}

	@Override
	public InventoryView openEnchanting(Location location, boolean force) {
		return actualPlayer.openEnchanting(location, force);
	}

	@Override
	public void openInventory(@NotNull InventoryView inventory) {
		actualPlayer.openInventory(inventory);
	}

	@Override
	public InventoryView openMerchant(@NotNull Villager trader, boolean force) {
		return actualPlayer.openMerchant(trader, force);
	}

	@Override
	public InventoryView openMerchant(@NotNull Merchant merchant, boolean force) {
		return actualPlayer.openMerchant(merchant, force);
	}

	@Override
	public void closeInventory() {
		actualPlayer.closeInventory();
	}

	@Override
	@Deprecated
	public @NotNull ItemStack getItemInHand() {
		return actualPlayer.getItemInHand();
	}

	@Override
	@Deprecated
	public void setItemInHand(ItemStack item) {
		actualPlayer.setItemInHand(item);
	}

	@Override
	public @NotNull ItemStack getItemOnCursor() {
		return actualPlayer.getItemOnCursor();
	}

	@Override
	public void setItemOnCursor(ItemStack item) {
		actualPlayer.setItemOnCursor(item);
	}

	@Override
	public boolean hasCooldown(@NotNull Material material) {
		return actualPlayer.hasCooldown(material);
	}

	@Override
	public int getCooldown(@NotNull Material material) {
		return actualPlayer.getCooldown(material);
	}

	@Override
	public void setCooldown(@NotNull Material material, int ticks) {
		actualPlayer.setCooldown(material, ticks);
	}

	@Override
	public int getSleepTicks() {
		return actualPlayer.getSleepTicks();
	}

	@Override
	public Location getBedSpawnLocation() {
		return actualPlayer.getBedSpawnLocation();
	}

	@Override
	public void setBedSpawnLocation(Location location) {
		actualPlayer.setBedSpawnLocation(location);
	}

	@Override
	public void setBedSpawnLocation(Location location, boolean force) {
		actualPlayer.setBedSpawnLocation(location, force);
	}

	@Override
	public boolean sleep(@NotNull Location location, boolean force) {
		return actualPlayer.sleep(location, force);
	}

	@Override
	public void wakeup(boolean setSpawnLocation) {
		actualPlayer.wakeup(setSpawnLocation);
	}

	@Override
	public @NotNull Location getBedLocation() {
		return actualPlayer.getBedLocation();
	}

	@Override
	public @NotNull GameMode getGameMode() {
		return actualPlayer.getGameMode();
	}

	@Override
	public void setGameMode(@NotNull GameMode mode) {
		actualPlayer.setGameMode(mode);
	}

	@Override
	public boolean isBlocking() {
		return actualPlayer.isBlocking();
	}

	@Override
	public boolean isHandRaised() {
		return actualPlayer.isHandRaised();
	}

	@Override
	public int getExpToLevel() {
		return actualPlayer.getExpToLevel();
	}

	@Override
	public boolean discoverRecipe(@NotNull NamespacedKey recipe) {
		return actualPlayer.discoverRecipe(recipe);
	}

	@Override
	public int discoverRecipes(@NotNull Collection<NamespacedKey> recipes) {
		return actualPlayer.discoverRecipes(recipes);
	}

	@Override
	public boolean undiscoverRecipe(@NotNull NamespacedKey recipe) {
		return actualPlayer.undiscoverRecipe(recipe);
	}

	@Override
	public int undiscoverRecipes(@NotNull Collection<NamespacedKey> recipes) {
		return actualPlayer.undiscoverRecipes(recipes);
	}

	@Override
	public boolean hasDiscoveredRecipe(@NotNull NamespacedKey recipe) {
		return actualPlayer.hasDiscoveredRecipe(recipe);
	}

	@Override
	public @NotNull Set<NamespacedKey> getDiscoveredRecipes() {
		return actualPlayer.getDiscoveredRecipes();
	}

	@Override
	@Deprecated
	public Entity getShoulderEntityLeft() {
		return actualPlayer.getShoulderEntityLeft();
	}

	@Override
	@Deprecated
	public void setShoulderEntityLeft(Entity entity) {
		actualPlayer.setShoulderEntityLeft(entity);
	}

	@Override
	@Deprecated
	public Entity getShoulderEntityRight() {
		return actualPlayer.getShoulderEntityRight();
	}

	@Override
	@Deprecated
	public void setShoulderEntityRight(Entity entity) {
		actualPlayer.setShoulderEntityRight(entity);
	}

	@Override
	public boolean dropItem(boolean dropAll) {
		return actualPlayer.dropItem(dropAll);
	}

	@Override
	public double getEyeHeight() {
		return actualPlayer.getEyeHeight();
	}

	@Override
	public double getEyeHeight(boolean ignorePose) {
		return actualPlayer.getEyeHeight(ignorePose);
	}

	@Override
	public @NotNull Location getEyeLocation() {
		return actualPlayer.getEyeLocation();
	}

	@Override
	public @NotNull List<Block> getLineOfSight(Set<Material> transparent, int maxDistance) {
		return actualPlayer.getLineOfSight(transparent, maxDistance);
	}

	@Override
	public @NotNull Block getTargetBlock(Set<Material> transparent, int maxDistance) {
		return actualPlayer.getTargetBlock(transparent, maxDistance);
	}

	@Override
	public @NotNull List<Block> getLastTwoTargetBlocks(Set<Material> transparent, int maxDistance) {
		return actualPlayer.getLastTwoTargetBlocks(transparent, maxDistance);
	}

	@Override
	public Block getTargetBlockExact(int maxDistance) {
		return actualPlayer.getTargetBlockExact(maxDistance);
	}

	@Override
	public Block getTargetBlockExact(int maxDistance, @NotNull FluidCollisionMode fluidCollisionMode) {
		return actualPlayer.getTargetBlockExact(maxDistance, fluidCollisionMode);
	}

	@Override
	public RayTraceResult rayTraceBlocks(double maxDistance) {
		return actualPlayer.rayTraceBlocks(maxDistance);
	}

	@Override
	public RayTraceResult rayTraceBlocks(double maxDistance, @NotNull FluidCollisionMode fluidCollisionMode) {
		return actualPlayer.rayTraceBlocks(maxDistance, fluidCollisionMode);
	}

	@Override
	public int getRemainingAir() {
		return actualPlayer.getRemainingAir();
	}

	@Override
	public void setRemainingAir(int ticks) {
		actualPlayer.setRemainingAir(ticks);
	}

	@Override
	public int getMaximumAir() {
		return actualPlayer.getMaximumAir();
	}

	@Override
	public void setMaximumAir(int ticks) {
		actualPlayer.setMaximumAir(ticks);
	}

	@Override
	public int getArrowCooldown() {
		return actualPlayer.getArrowCooldown();
	}

	@Override
	public void setArrowCooldown(int ticks) {
		actualPlayer.setArrowCooldown(ticks);
	}

	@Override
	public int getArrowsInBody() {
		return actualPlayer.getArrowsInBody();
	}

	@Override
	public void setArrowsInBody(int count) {
		actualPlayer.setArrowsInBody(count);
	}

	@Override
	public int getMaximumNoDamageTicks() {
		return actualPlayer.getMaximumNoDamageTicks();
	}

	@Override
	public void setMaximumNoDamageTicks(int ticks) {
		actualPlayer.setMaximumNoDamageTicks(ticks);
	}

	@Override
	public double getLastDamage() {
		return actualPlayer.getLastDamage();
	}

	@Override
	public void setLastDamage(double damage) {
		actualPlayer.setLastDamage(damage);
	}

	@Override
	public int getNoDamageTicks() {
		return actualPlayer.getNoDamageTicks();
	}

	@Override
	public void setNoDamageTicks(int ticks) {
		actualPlayer.setNoDamageTicks(ticks);
	}

	@Override
	public Player getKiller() {
		return actualPlayer.getKiller();
	}

	@Override
	public boolean addPotionEffect(@NotNull PotionEffect effect) {
		return actualPlayer.addPotionEffect(effect);
	}

	@Override
	@Deprecated
	public boolean addPotionEffect(@NotNull PotionEffect effect, boolean force) {
		return actualPlayer.addPotionEffect(effect, force);
	}

	@Override
	public boolean addPotionEffects(@NotNull Collection<PotionEffect> effects) {
		return actualPlayer.addPotionEffects(effects);
	}

	@Override
	public boolean hasPotionEffect(@NotNull PotionEffectType type) {
		return actualPlayer.hasPotionEffect(type);
	}

	@Override
	public PotionEffect getPotionEffect(@NotNull PotionEffectType type) {
		return actualPlayer.getPotionEffect(type);
	}

	@Override
	public void removePotionEffect(@NotNull PotionEffectType type) {
		actualPlayer.removePotionEffect(type);
	}

	@Override
	public @NotNull Collection<PotionEffect> getActivePotionEffects() {
		return actualPlayer.getActivePotionEffects();
	}

	@Override
	public boolean hasLineOfSight(@NotNull Entity other) {
		return actualPlayer.hasLineOfSight(other);
	}

	@Override
	public boolean getRemoveWhenFarAway() {
		return actualPlayer.getRemoveWhenFarAway();
	}

	@Override
	public void setRemoveWhenFarAway(boolean remove) {
		actualPlayer.setRemoveWhenFarAway(remove);
	}

	@Override
	public EntityEquipment getEquipment() {
		return actualPlayer.getEquipment();
	}

	@Override
	public void setCanPickupItems(boolean pickup) {
		actualPlayer.setCanPickupItems(pickup);
	}

	@Override
	public boolean getCanPickupItems() {
		return actualPlayer.getCanPickupItems();
	}

	@Override
	public boolean isLeashed() {
		return actualPlayer.isLeashed();
	}

	@Override
	public @NotNull Entity getLeashHolder() throws IllegalStateException {
		return actualPlayer.getLeashHolder();
	}

	@Override
	public boolean setLeashHolder(Entity holder) {
		return actualPlayer.setLeashHolder(holder);
	}

	@Override
	public boolean isGliding() {
		return actualPlayer.isGliding();
	}

	@Override
	public void setGliding(boolean gliding) {
		actualPlayer.setGliding(gliding);
	}

	@Override
	public boolean isSwimming() {
		return actualPlayer.isSwimming();
	}

	@Override
	public void setSwimming(boolean swimming) {
		actualPlayer.setSwimming(swimming);
	}

	@Override
	public boolean isRiptiding() {
		return actualPlayer.isRiptiding();
	}

	@Override
	public boolean isSleeping() {
		return actualPlayer.isSleeping();
	}

	@Override
	public void setAI(boolean ai) {
		actualPlayer.setAI(ai);
	}

	@Override
	public boolean hasAI() {
		return actualPlayer.hasAI();
	}

	@Override
	public void attack(@NotNull Entity target) {
		actualPlayer.attack(target);
	}

	@Override
	public void swingMainHand() {
		actualPlayer.swingMainHand();
	}

	@Override
	public void swingOffHand() {
		actualPlayer.swingOffHand();
	}

	@Override
	public void setCollidable(boolean collidable) {
		actualPlayer.setCollidable(collidable);
	}

	@Override
	public boolean isCollidable() {
		return actualPlayer.isCollidable();
	}

	@Override
	public @NotNull Set<UUID> getCollidableExemptions() {
		return actualPlayer.getCollidableExemptions();
	}

	@Override
	public <T> T getMemory(@NotNull MemoryKey<T> memoryKey) {
		return actualPlayer.getMemory(memoryKey);
	}

	@Override
	public <T> void setMemory(@NotNull MemoryKey<T> memoryKey, T memoryValue) {
		actualPlayer.setMemory(memoryKey, memoryValue);
	}

	@Override
	public @NotNull EntityCategory getCategory() {
		return actualPlayer.getCategory();
	}

	@Override
	public void setInvisible(boolean invisible) {
		actualPlayer.setInvisible(invisible);
	}

	@Override
	public boolean isInvisible() {
		return actualPlayer.isInvisible();
	}

	@Override
	public AttributeInstance getAttribute(@NotNull Attribute attribute) {
		return actualPlayer.getAttribute(attribute);
	}

	@Override
	public void damage(double amount) {
		actualPlayer.damage(amount);
	}

	@Override
	public void damage(double amount, Entity source) {
		actualPlayer.damage(amount, source);
	}

	@Override
	public double getHealth() {
		return actualPlayer.getHealth();
	}

	@Override
	public void setHealth(double health) {
		actualPlayer.setHealth(health);
	}

	@Override
	public double getAbsorptionAmount() {
		return actualPlayer.getAbsorptionAmount();
	}

	@Override
	public void setAbsorptionAmount(double amount) {
		actualPlayer.setAbsorptionAmount(amount);
	}

	@Override
	@Deprecated
	public double getMaxHealth() {
		return actualPlayer.getMaxHealth();
	}

	@Override
	@Deprecated
	public void setMaxHealth(double health) {
		actualPlayer.setMaxHealth(health);
	}

	@Override
	@Deprecated
	public void resetMaxHealth() {
		actualPlayer.resetMaxHealth();
	}

	@Override
	public @NotNull Location getLocation() {
		return actualPlayer.getLocation();
	}

	@Override
	public Location getLocation(Location loc) {
		return actualPlayer.getLocation(loc);
	}

	@Override
	public void setVelocity(@NotNull Vector velocity) {
		actualPlayer.setVelocity(velocity);
	}

	@Override
	public @NotNull Vector getVelocity() {
		return actualPlayer.getVelocity();
	}

	@Override
	public double getHeight() {
		return actualPlayer.getHeight();
	}

	@Override
	public double getWidth() {
		return actualPlayer.getWidth();
	}

	@Override
	public @NotNull BoundingBox getBoundingBox() {
		return actualPlayer.getBoundingBox();
	}

	@Override
	@Deprecated
	public boolean isOnGround() {
		return actualPlayer.isOnGround();
	}

	@Override
	public boolean isInWater() {
		return actualPlayer.isInWater();
	}

	@Override
	public @NotNull World getWorld() {
		return actualPlayer.getWorld();
	}

	@Override
	public void setRotation(float yaw, float pitch) {
		actualPlayer.setRotation(yaw, pitch);
	}

	@Override
	public boolean teleport(@NotNull Location location) {
		return actualPlayer.teleport(location);
	}

	@Override
	public boolean teleport(@NotNull Location location, PlayerTeleportEvent.@NotNull TeleportCause cause) {
		return actualPlayer.teleport(location, cause);
	}

	@Override
	public boolean teleport(@NotNull Entity destination) {
		return actualPlayer.teleport(destination);
	}

	@Override
	public boolean teleport(@NotNull Entity destination, PlayerTeleportEvent.@NotNull TeleportCause cause) {
		return actualPlayer.teleport(destination, cause);
	}

	@Override
	public @NotNull List<Entity> getNearbyEntities(double x, double y, double z) {
		return actualPlayer.getNearbyEntities(x, y, z);
	}

	@Override
	public int getEntityId() {
		return actualPlayer.getEntityId();
	}

	@Override
	public int getFireTicks() {
		return actualPlayer.getFireTicks();
	}

	@Override
	public int getMaxFireTicks() {
		return actualPlayer.getMaxFireTicks();
	}

	@Override
	public void setFireTicks(int ticks) {
		actualPlayer.setFireTicks(ticks);
	}

	@Override
	public void remove() {
		actualPlayer.remove();
	}

	@Override
	public boolean isDead() {
		return actualPlayer.isDead();
	}

	@Override
	public boolean isValid() {
		return actualPlayer.isValid();
	}

	@Override
	public @NotNull Server getServer() {
		return actualPlayer.getServer();
	}

	@Override
	@Deprecated
	public boolean isPersistent() {
		return actualPlayer.isPersistent();
	}

	@Override
	@Deprecated
	public void setPersistent(boolean persistent) {
		actualPlayer.setPersistent(persistent);
	}

	@Override
	@Deprecated
	public Entity getPassenger() {
		return actualPlayer.getPassenger();
	}

	@Override
	@Deprecated
	public boolean setPassenger(@NotNull Entity passenger) {
		return actualPlayer.setPassenger(passenger);
	}

	@Override
	public @NotNull List<Entity> getPassengers() {
		return actualPlayer.getPassengers();
	}

	@Override
	public boolean addPassenger(@NotNull Entity passenger) {
		return actualPlayer.addPassenger(passenger);
	}

	@Override
	public boolean removePassenger(@NotNull Entity passenger) {
		return actualPlayer.removePassenger(passenger);
	}

	@Override
	public boolean isEmpty() {
		return actualPlayer.isEmpty();
	}

	@Override
	public boolean eject() {
		return actualPlayer.eject();
	}

	@Override
	public float getFallDistance() {
		return actualPlayer.getFallDistance();
	}

	@Override
	public void setFallDistance(float distance) {
		actualPlayer.setFallDistance(distance);
	}

	@Override
	public void setLastDamageCause(EntityDamageEvent event) {
		actualPlayer.setLastDamageCause(event);
	}

	@Override
	public EntityDamageEvent getLastDamageCause() {
		return actualPlayer.getLastDamageCause();
	}

	@Override
	public int getTicksLived() {
		return actualPlayer.getTicksLived();
	}

	@Override
	public void setTicksLived(int value) {
		actualPlayer.setTicksLived(value);
	}

	@Override
	public void playEffect(@NotNull EntityEffect type) {
		actualPlayer.playEffect(type);
	}

	@Override
	public @NotNull EntityType getType() {
		return actualPlayer.getType();
	}

	@Override
	public boolean isInsideVehicle() {
		return actualPlayer.isInsideVehicle();
	}

	@Override
	public boolean leaveVehicle() {
		return actualPlayer.leaveVehicle();
	}

	@Override
	public Entity getVehicle() {
		return actualPlayer.getVehicle();
	}

	@Override
	public void setCustomNameVisible(boolean flag) {
		actualPlayer.setCustomNameVisible(flag);
	}

	@Override
	public boolean isCustomNameVisible() {
		return actualPlayer.isCustomNameVisible();
	}

	@Override
	public void setGlowing(boolean flag) {
		actualPlayer.setGlowing(flag);
	}

	@Override
	public boolean isGlowing() {
		return actualPlayer.isGlowing();
	}

	@Override
	public void setInvulnerable(boolean flag) {
		actualPlayer.setInvulnerable(flag);
	}

	@Override
	public boolean isInvulnerable() {
		return actualPlayer.isInvulnerable();
	}

	@Override
	public boolean isSilent() {
		return actualPlayer.isSilent();
	}

	@Override
	public void setSilent(boolean flag) {
		actualPlayer.setSilent(flag);
	}

	@Override
	public boolean hasGravity() {
		return actualPlayer.hasGravity();
	}

	@Override
	public void setGravity(boolean gravity) {
		actualPlayer.setGravity(gravity);
	}

	@Override
	public int getPortalCooldown() {
		return actualPlayer.getPortalCooldown();
	}

	@Override
	public void setPortalCooldown(int cooldown) {
		actualPlayer.setPortalCooldown(cooldown);
	}

	@Override
	public @NotNull Set<String> getScoreboardTags() {
		return actualPlayer.getScoreboardTags();
	}

	@Override
	public boolean addScoreboardTag(@NotNull String tag) {
		return actualPlayer.addScoreboardTag(tag);
	}

	@Override
	public boolean removeScoreboardTag(@NotNull String tag) {
		return actualPlayer.removeScoreboardTag(tag);
	}

	@Override
	public @NotNull PistonMoveReaction getPistonMoveReaction() {
		return actualPlayer.getPistonMoveReaction();
	}

	@Override
	public @NotNull BlockFace getFacing() {
		return actualPlayer.getFacing();
	}

	@Override
	public @NotNull Pose getPose() {
		return actualPlayer.getPose();
	}

	@Override
	public void setMetadata(@NotNull String metadataKey, @NotNull MetadataValue newMetadataValue) {
		actualPlayer.setMetadata(metadataKey, newMetadataValue);
	}

	@Override
	public @NotNull List<MetadataValue> getMetadata(@NotNull String metadataKey) {
		return actualPlayer.getMetadata(metadataKey);
	}

	@Override
	public boolean hasMetadata(@NotNull String metadataKey) {
		return actualPlayer.hasMetadata(metadataKey);
	}

	@Override
	public void removeMetadata(@NotNull String metadataKey, @NotNull Plugin owningPlugin) {
		actualPlayer.removeMetadata(metadataKey, owningPlugin);
	}

	@Override
	public void sendMessage(@NotNull String message) {
		actualPlayer.sendMessage(message);
	}

	@Override
	public void sendMessage(String[] messages) {
		actualPlayer.sendMessage(messages);
	}

	@Override
	public void sendMessage(@Nullable UUID sender, @NotNull String message) {
		actualPlayer.sendMessage(sender, message);
	}

	@Override
	public void sendMessage(@Nullable UUID sender, @NotNull String[] messages) {
		actualPlayer.sendMessage(sender, messages);
	}

	@Override
	public boolean isPermissionSet(@NotNull String name) {
		return actualPlayer.isPermissionSet(name);
	}

	@Override
	public boolean isPermissionSet(@NotNull Permission perm) {
		return actualPlayer.isPermissionSet(perm);
	}

	@Override
	public boolean hasPermission(@NotNull String name) {
		return actualPlayer.hasPermission(name);
	}

	@Override
	public boolean hasPermission(@NotNull Permission perm) {
		return actualPlayer.hasPermission(perm);
	}

	@Override
	public @NotNull PermissionAttachment addAttachment(@NotNull Plugin plugin, @NotNull String name, boolean value) {
		return actualPlayer.addAttachment(plugin, name, value);
	}

	@Override
	public @NotNull PermissionAttachment addAttachment(@NotNull Plugin plugin) {
		return actualPlayer.addAttachment(plugin);
	}

	@Override
	public PermissionAttachment addAttachment(@NotNull Plugin plugin, @NotNull String name, boolean value, int ticks) {
		return actualPlayer.addAttachment(plugin, name, value, ticks);
	}

	@Override
	public PermissionAttachment addAttachment(@NotNull Plugin plugin, int ticks) {
		return actualPlayer.addAttachment(plugin, ticks);
	}

	@Override
	public void removeAttachment(@NotNull PermissionAttachment attachment) {
		actualPlayer.removeAttachment(attachment);
	}

	@Override
	public void recalculatePermissions() {
		actualPlayer.recalculatePermissions();
	}

	@Override
	public @NotNull Set<PermissionAttachmentInfo> getEffectivePermissions() {
		return actualPlayer.getEffectivePermissions();
	}

	@Override
	public boolean isOp() {
		return actualPlayer.isOp();
	}

	@Override
	public void setOp(boolean value) {
		actualPlayer.setOp(value);
	}

	@Override
	public String getCustomName() {
		return actualPlayer.getCustomName();
	}

	@Override
	public void setCustomName(String name) {
		actualPlayer.setCustomName(name);
	}

	@Override
	public @NotNull PersistentDataContainer getPersistentDataContainer() {
		return actualPlayer.getPersistentDataContainer();
	}

	@Override
	public <T extends Projectile> @NotNull T launchProjectile(@NotNull Class<? extends T> projectile) {
		return actualPlayer.launchProjectile(projectile);
	}

	@Override
	public <T extends Projectile> @NotNull T launchProjectile(@NotNull Class<? extends T> projectile, Vector velocity) {
		return actualPlayer.launchProjectile(projectile, velocity);
	}

	@Override
	public boolean isConversing() {
		return actualPlayer.isConversing();
	}

	@Override
	public void acceptConversationInput(@NotNull String input) {
		actualPlayer.acceptConversationInput(input);
	}

	@Override
	public boolean beginConversation(@NotNull Conversation conversation) {
		return actualPlayer.beginConversation(conversation);
	}

	@Override
	public void abandonConversation(@NotNull Conversation conversation) {
		actualPlayer.abandonConversation(conversation);
	}

	@Override
	public void abandonConversation(@NotNull Conversation conversation, @NotNull ConversationAbandonedEvent details) {
		actualPlayer.abandonConversation(conversation, details);
	}

	@Override
	public boolean isOnline() {
		return actualPlayer.isOnline();
	}

	@Override
	public boolean isBanned() {
		return actualPlayer.isBanned();
	}

	@Override
	public boolean isWhitelisted() {
		return actualPlayer.isWhitelisted();
	}

	@Override
	public void setWhitelisted(boolean value) {
		actualPlayer.setWhitelisted(value);
	}

	@Override
	public Player getPlayer() {
		return actualPlayer.getPlayer();
	}

	@Override
	public long getFirstPlayed() {
		return actualPlayer.getFirstPlayed();
	}

	@Override
	@Deprecated
	public long getLastPlayed() {
		return actualPlayer.getLastPlayed();
	}

	@Override
	public boolean hasPlayedBefore() {
		return actualPlayer.hasPlayedBefore();
	}

	@Override
	public void incrementStatistic(@NotNull Statistic statistic) throws IllegalArgumentException {
		actualPlayer.incrementStatistic(statistic);
	}

	@Override
	public void decrementStatistic(@NotNull Statistic statistic) throws IllegalArgumentException {
		actualPlayer.decrementStatistic(statistic);
	}

	@Override
	public void incrementStatistic(@NotNull Statistic statistic, int amount) throws IllegalArgumentException {
		actualPlayer.incrementStatistic(statistic, amount);
	}

	@Override
	public void decrementStatistic(@NotNull Statistic statistic, int amount) throws IllegalArgumentException {
		actualPlayer.decrementStatistic(statistic, amount);
	}

	@Override
	public void setStatistic(@NotNull Statistic statistic, int newValue) throws IllegalArgumentException {
		actualPlayer.setStatistic(statistic, newValue);
	}

	@Override
	public int getStatistic(@NotNull Statistic statistic) throws IllegalArgumentException {
		return actualPlayer.getStatistic(statistic);
	}

	@Override
	public void incrementStatistic(@NotNull Statistic statistic, @NotNull Material material) throws IllegalArgumentException {
		actualPlayer.incrementStatistic(statistic, material);
	}

	@Override
	public void decrementStatistic(@NotNull Statistic statistic, @NotNull Material material) throws IllegalArgumentException {
		actualPlayer.decrementStatistic(statistic, material);
	}

	@Override
	public int getStatistic(@NotNull Statistic statistic, @NotNull Material material) throws IllegalArgumentException {
		return actualPlayer.getStatistic(statistic, material);
	}

	@Override
	public void incrementStatistic(@NotNull Statistic statistic, @NotNull Material material, int amount) throws IllegalArgumentException {
		actualPlayer.incrementStatistic(statistic, material, amount);
	}

	@Override
	public void decrementStatistic(@NotNull Statistic statistic, @NotNull Material material, int amount) throws IllegalArgumentException {
		actualPlayer.decrementStatistic(statistic, material, amount);
	}

	@Override
	public void setStatistic(@NotNull Statistic statistic, @NotNull Material material, int newValue) throws IllegalArgumentException {
		actualPlayer.setStatistic(statistic, material, newValue);
	}

	@Override
	public void incrementStatistic(@NotNull Statistic statistic, @NotNull EntityType entityType) throws IllegalArgumentException {
		actualPlayer.incrementStatistic(statistic, entityType);
	}

	@Override
	public void decrementStatistic(@NotNull Statistic statistic, @NotNull EntityType entityType) throws IllegalArgumentException {
		actualPlayer.decrementStatistic(statistic, entityType);
	}

	@Override
	public int getStatistic(@NotNull Statistic statistic, @NotNull EntityType entityType) throws IllegalArgumentException {
		return actualPlayer.getStatistic(statistic, entityType);
	}

	@Override
	public void incrementStatistic(@NotNull Statistic statistic, @NotNull EntityType entityType, int amount) throws IllegalArgumentException {
		actualPlayer.incrementStatistic(statistic, entityType, amount);
	}

	@Override
	public void decrementStatistic(@NotNull Statistic statistic, @NotNull EntityType entityType, int amount) {
		actualPlayer.decrementStatistic(statistic, entityType, amount);
	}

	@Override
	public void setStatistic(@NotNull Statistic statistic, @NotNull EntityType entityType, int newValue) {
		actualPlayer.setStatistic(statistic, entityType, newValue);
	}

	@Override
	public @NotNull Map<String, Object> serialize() {
		return actualPlayer.serialize();
	}

	@Override
	public void sendPluginMessage(@NotNull Plugin source, @NotNull String channel, byte[] message) {
		actualPlayer.sendPluginMessage(source, channel, message);
	}

	@Override
	public @NotNull Set<String> getListeningPluginChannels() {
		return actualPlayer.getListeningPluginChannels();
	}
}
